### ISSUE TITLE
Webpack v4 Support

### ISSUE THREAD

**Issue by teod** [webpack-contrib/stylelint-webpack-plugin#137]
`TypeError: Cannot read property 'plugin' of undefined
    at stylelintWebpackPlugin.runCompilation (node_modules/stylelint-webpack-plugin/lib/run-compilation.js:38:12)`

**Comment by wellyshen** [comment]
I have the same issue.

**Comment by CinKon** [comment]
I get this only in Dev-Mode. Production Build runs just fine.
Maybe it's related to some Middleware/HMR?

**Comment by andreyvolokitin** [comment]
@CinKon the error stack mentions a lot of `webpack-dev-server`...

**Comment by lerit** [comment]
same issue,

**Comment by shellscape** [comment]
@andreyvolokitin @lerit @teod @wellyshen @CinKon you might consider trying [`webpack-serve`](https://github.com/webpack-contrib/webpack-serve), as it's a little less brittle than webpack-dev-server, but this one looks like an issue in the stylelint plugin itself.

**Comment by bymathias** [comment]
same issue

**Comment by shellscape** [comment]
@bymathias please don't post _"me too"_ or _"same issue"_ replies. Instead, use the reaction buttons on the original post.

**Comment by wellyshen** [comment]
any update for this issue?

**Comment by shellscape** [comment]
@wellyshen when there are updates Github will display them in the issue or any linked/referenced Pull Requests. Until then, please be patient while the maintainers work around their schedule to get this update in.

**Comment by shellscape** [comment]
Just wanted to drop a small comment, not really an update, but to let everyone know that we're not hiding from this one:

The developer who has the active PR (#140) to resolve this has vanished and we're doing our due diligence to get ahold of them so we can proceed with their PR. It's unfortunately blocking a fix at this very moment, but we've got to give them the chance to pop back up and respond. We all know how important getting this fixed is and that it's holding up a ton of users, and we're on top of it.

**Comment by shellscape** [comment]
#144 is ready and awaiting review and merge. Once that happens, we'll publish a patch release for Webpack v4. Should be within the next day or so.

**Comment by shellscape** [comment]
Closed in #144. Will be publishing a patch release shortly.

**Please note** that the next release of this plugin will likely be a major version that will put the plugin requirement in line with the rest of the webpack ecosystem standard. That means minimum requirements will be Node v6+ and Webpack v4+.

**Comment by mttmccb** [comment]
Where can I track when the 0.10.4 is released on NPM? Presumably it's not because of breaking changes?

**Comment by shellscape** [comment]
@mttmccb apologies, but I can't understand what you're trying to ask?

**Comment by mttmccb** [comment]
Sorry ignore me, last time I checked it was only installing 0.10.3 so I though it hadn't been released yet, it's fine now.
