### ISSUE TITLE
Wrong documentation for `emitErrors`

### ISSUE THREAD

**Issue by sdvg** [webpack-contrib/stylelint-webpack-plugin#138]
The documentation says `emitErrors` defaults to `true`, but it makes a difference if you set it to `true` instead of omitting the option.

I use the NoEmitOnErrorsPlugin. When I set `emitErrors: true` it works correctly, when I don't (leave it undefined), it shows the errors but generates my `dist` folder.

Maybe not related, but what I tried before was setting `failOnError: true`. This successfully breaks my build but shows me the following instead of an useful error message:

> node:50144) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'toString' of undefined
> (node:50144) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jeron-diovis** [comment]
For me, in case of using `failOnError: true`, it says following:

```sh
Error: Failed because of a stylelint error.

    at linter.then (/path/to/project/node_modules/stylelint-webpack-plugin/lib/run-compilation.js:39:14)
    at <anonymous>
```

And no detailed errors report at all.
