### ISSUE TITLE
Support for StyleLint 9.x as peerDependency

### ISSUE THREAD

**Issue by igor-savin-ht** [webpack-contrib/stylelint-webpack-plugin#149]
Currently plugin depends on ^8.0.0. Are there any particular reasons why 9.x.y is not supported?

**Comment by shellscape** [comment]
yes, the plugin doesn't function properly with 9.x. The plugin also allows use on Node 4.x, which stylelint 9.x has dropped, which causes complications. We're working on an update for a major version on which these issues will be resolved.

**Comment by brneto** [comment]
Does `stylelint-webpack-plugin` haven't improved support to stylelint v9 yet? May I do something to help on that?

**Comment by shellscape** [comment]
@brneto as far as I know support for v9 hasn't been added yet. if you would like to submit a Pull Request we'd be happy to review it.

**Comment by brneto** [comment]
I’d like to do that, but I’d like a little help to where to start. I’ve seen others contributors trying to update the dependency, but all did a downgrade after. What they did wrong and what I should don’t do to not make the same mistakes they did?

**Comment by brneto** [comment]
@shellscape How about Node 4.x support? It can be dropped as stylelint did?

**Comment by shellscape** [comment]
@brneto if stylelint dropped it then there's a strong case to drop it here as well. I would back that choice. fwiw webpack no longer supports Node 4, so that's the two big platforms that the plugin interacts with.

**Comment by brneto** [comment]
The package.json of stylelint is saying: ‘"engines": {
    "node": ">=6"
  },’

**Comment by brneto** [comment]
@shellscape Which issues have you faced when tried to update to Stylelint 9?

**Comment by shellscape** [comment]
Last I tried it just asploded. Smoke and everything.

**Comment by brneto** [comment]
Which version of Node are you using to test?

**Comment by shellscape** [comment]
Brother I'm pretty much just a custodian on this project. When I did the big webpack-defaults update and merged the other pending PRs, I attempted a stylelint version update and the tests were not happy, so I backed off that. Probably Node v9 at the time? If there's a PR to update that and everything works, it gets my approval.

**Comment by edmorley** [comment]
For those not subscribed to the PR -- The PR updating the peer dependency (#160) has now been merged, so once there is a new release, this issue can be closed.

**Comment by avrelaun** [comment]
Could we have a new release, or help to make it happen ?

**Comment by evilebottnawi** [comment]
@avrelaun PR welcome :+1:

**Comment by avrelaun** [comment]
@evilebottnawi https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/164 I do not think I can do more after that since I don't believe I have the rights to tag, add changelog to tag & publish to npm...

**Comment by avrelaun** [comment]
I cannot seem to figure out what's the problem with the build, could someone help ?

**Comment by jackwilsdon** [comment]
This seems to be working fine for me as of 5ae9467ef6eaabfb42bd2e77ce34f8d380095601, all the tests pass and I'm using it in my Webpack 4 configuration without issue.

Could this get tagged and published?

**Comment by brneto** [comment]
@edmorley @evilebottnawi There is some mistake here, because of the `package.json` file from `yarn add -D stylelint-webpack-plugin` is bringing this plugin version 0.10.5, but not bringing the same `peerDependencies` and `devDependencies` as in PR #160. Any Idea why is that happening and How can I fix it?

Yarn 1.9.4

**Comment by jackwilsdon** [comment]
@brneto no new version has been tagged from those changes, so what you're seeing is the `package.json` from before the PR was merged. It's why I asked above to get this tagged and merged :+1:

**Comment by brneto** [comment]
@edmorley @evilebottnawi When are you planning to release the new version to fix this warning? Any probable date?

**Comment by edmorley** [comment]
I'm not a maintainer of this project, so unable to make a new release.

**Comment by jackwilsdon** [comment]
Looks like @d3viant0ne, @JaKXz, @shellscape and @vieron are the ones to ask.

**Comment by evilebottnawi** [comment]
A lot of works guys, feel free PR, also we search developers to maintenance this plugin, ping me if you interested.

**Comment by avrelaun** [comment]
https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/164 ?

**Comment by jjeising** [comment]
Can we do anything to move this forward?

**Comment by jole7** [comment]
> Can we do anything to move this forward?

Give up & look elsewhere.

Coming up on a year.  Wish they hadn't railroaded the most active maintainer, right?

maybe this from @cascornelissen

   https://github.com/cascornelissen/stylelint-bare-webpack-plugin#readme

?

**Comment by brneto** [comment]
@jole7 Any other options, you might know? I what to check some more options to I change to.

**Comment by jole7** [comment]
@brneto 
I use webpack because it integrates assets bundling.  For me that includes ALL my assets -- & linting BOTH styles & scripts.
When that stops working -- case in point here -- webpack is no longer particularly useful to me.
Doesn't seem like this is getting fixed any time soon.  It's considered 'community' not 'official'.  Lots of other projects are trying to work around it.
The 'other' option I'm looking at right now is NOT using webpack, but other bundling tools.

**Comment by brneto** [comment]
@jole7 would mind give some suggestions?

**Comment by rowild** [comment]
@jole7 Thanks for that link you posted! Need to try that one. Do you already have some experience with it? Is it a worthy replacement?

**Comment by jole7** [comment]
no real 'suggestions' to give, or any evaluations of 'worthiness'.  I've not used anything else yet.  Well, gulp -- but that's where I _started_ & left.

So far, I've decided to give Parcel.js a closer look:

https://parceljs.org/
https://medium.com/@ibrahimbutt/if-youve-ever-configured-webpack-parcel-will-blow-your-mind-b615468cee78

**Comment by rowild** [comment]
Didn't know that Parcel already has tree shaking implemented!
