### ISSUE TITLE
How to get the detailed error info when ‘failOnError’ setted to true？

### ISSUE THREAD

**Issue by qianjunsteve** [webpack-contrib/stylelint-webpack-plugin#151]
When the stylelint error happen, I want stop the webpack process and get the detailed error info. But if
I set failOnError to true. The log is not clear：

Error: Failed because of a stylelint error.

    at linterSuccess (/Users/lidasong/Documents/projects/appstore-rn/h5/node_modules/stylelint-webpack-plugin/lib/run-compilation.js:39:14)

**Comment by AndrewCraswell** [comment]
I'm receiving this as well.

**Comment by hirantha129** [comment]
Any update on this?

**Comment by jason-symbiote** [comment]
@silbinarywolf Cheers man :)  I think `syntax` option may be the key here, as the default value is 'undefined'.

As what the stylelint user guide said:
"If you do not specify a syntax, non-standard syntaxes will be automatically inferred.
See the customSyntax option below if you would like to use stylelint with a custom syntax."

**Comment by MarcelRittershaus** [comment]
const StyleLint = new StyleLintPlugin({
  configFile:  path.resolve(__dirname, '../.stylelintrc.json'),
  files: ['/app/components/**/*.{scss,sass}'],
	failOnError: false,
	emitErrors: false,
	syntax: 'scss',
	quiet: false,
});
