### ISSUE TITLE
More restrictive peerDependencies in patch release

### ISSUE THREAD

**Issue by GreenGremlin** [webpack-contrib/stylelint-webpack-plugin#152]
Why was support for older versions of webpack dropped in a patch release? Patch releases should not contain breaking changes.

_Version 0.10.3_

``` json
"webpack": "^3 || ^2 || ^2.2.0-rc.0 || ^2.1.0-beta.0 || ^1.13.2"
```

_Version 0.10.4_

``` json
"webpack": "^1.13.2 || ^2.7.0 || ^3.11.0 || ^4.4.0"
```

I see the master branch has dropped support for all versions of webpack less than 4.4.0, this is very concerning as many of us are not yet ready to upgrade to webpack 4.

_master_

``` json
"webpack": "^4.4.0"
```

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.
