### ISSUE TITLE
Version 0.10.4 dropped support for some versions of webpack

### ISSUE THREAD

**Issue by GreenGremlin** [webpack-contrib/stylelint-webpack-plugin#153]
Why was support for older versions of webpack dropped in a patch release? Patch releases should not contain breaking changes.

``` diff
     "stylelint": "^8.0.0",
-    "webpack": "^3 || ^2 || ^2.2.0-rc.0 || ^2.1.0-beta.0 || ^1.13.2"
+    "webpack": "^1.13.2 || ^2.7.0 || ^3.11.0 || ^4.4.0"
```

I see the master branch has dropped support for all versions of webpack less than 4.4.0, this is very concerning as many of us are not yet ready to upgrade to webpack 4.

``` diff
   "peerDependencies": {
     "stylelint": "^8.0.0",
-    "webpack": "^1.13.2 || ^2.7.0 || ^3.11.0 || ^4.4.0"
+    "webpack": "^4.4.0"
```

* Operating System: Doesn't matter
* Node Version: 8.9.4
* NPM Version: 5.6.0
* webpack Version: 3.8.1
* stylelint-webpack-plugin Version: 0.10.4

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Expected Behavior

Version 0.10.4 should support all versions of webpack supported by version 0.10.3

### Actual Behavior

Version 0.10.4 dropped support for some versions of webpack.

**Comment by shellscape** [comment]
@GreenGremlin thanks for the issue :beer:

Yeah that looks like a regression. We'll try and get a patch out soon to correct that. For the time being, please hardcode your version to the previous patch version.

It's worth noting that the next version of the module _may_ be a major version in which only webpack@4 is supported. As modules in `webpack-contrib` get updated for version 4 support, the pattern has been to bump the major and minimum version of webpack.
