### ISSUE TITLE
Release latest version (0.10.5) in NPM

### ISSUE THREAD

**Issue by christophercr** [webpack-contrib/stylelint-webpack-plugin#155]
The latet version was released ([0.10.5](https://github.com/webpack-contrib/stylelint-webpack-plugin/releases/tag/v0.10.5)) but only in Github.

Could you please release it also in NPM?

**Comment by shellscape** [comment]
Sad panda 🐼 😢  You removed the issue template, so we have to close your issue as invalid. Please don't ignore Issue or Pull Request templates.
