### ISSUE TITLE
Release latest version (0.10.5) in NPM

### ISSUE THREAD

**Issue by christophercr** [webpack-contrib/stylelint-webpack-plugin#156]
* Operating System: ALL
* Node Version: ALL
* NPM Version: ALL
* webpack Version: 4.x
* stylelint-webpack-plugin Version: 0.10.4

This issue is for a:

- [X] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Expected Behavior
Version 0.10.5 available in NPM

### Actual Behavior
Version 0.10.5 not available in NPM

### How Do We Reproduce?
npm install stylelint-webpack-plugin@0.10.5

**Comment by shellscape** [comment]
According to npm it was published. Run:

```console
npm info stylelint-webpack-plugin
```

Which reveals this: `'0.10.5': '2018-05-10T18:43:31.161Z' },`

Your issue should have reported that the `dist-tags` were incorrect, as installing `@next` would have given you v0.10.5. I've now corrected the `dist-tags`.
