### ISSUE TITLE
Release version with latest changes

### ISSUE THREAD

**Issue by frosas** [webpack-contrib/stylelint-webpack-plugin#171]
This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [x] **modification** request

### Expected Behavior

Latest change (a dependency version bump) is released.

### Actual Behavior

It is not.

**Comment by evilebottnawi** [comment]
I am afraid version from master broken, can you manually test? And we can release

**Comment by S1019269** [comment]
Will the next version support stylelint ^9.0.0?
The current version needs stylelint@^8.0.0, but there is a vulnerability with braces. 
> stylelint > micromatch > braces 
https://npmjs.com/advisories/786

**Comment by frosas** [comment]
@evilebottnawi, what do you mean by "version from master broken"? Are you referring to "npm test", the CI pipeline, the code itself, ...? I guess you're referring to the pipeline as it's been failing in the latest builds. In that case, shouldn't it be fixed instead of resorting to manual testing?

@S1019269, yes, `master` already has such a version. All it's missing is a new npm version publication.

**Comment by ricardogobbosouza** [comment]
@evilebottnawi we need to release a version that accepts stylelint 9
Actually just need to release the version

**Comment by evilebottnawi** [comment]
@ricardogobbosouza in todo, try to find time tomorrow, don't worry

**Comment by ricardogobbosouza** [comment]
@evilebottnawi I don't have publishing permission

**Comment by evilebottnawi** [comment]
@ricardogobbosouza i will do release tomorrow
