### ISSUE TITLE
`fix` does not work with `lintDirtyModulesOnly` enabled

### ISSUE THREAD

**Issue by thasmo** [webpack-contrib/stylelint-webpack-plugin#173]
Using this doesn't fix source files.
```ts
const plugin = StyleLintPlugin({
	lintDirtyModulesOnly: true,
	fix: true,
});
```
It seems that `fix: true` does not have any effect.

**Comment by thasmo** [comment]
Oh, when setting `lintDirtyModulesOnly: false`, `fix: true` works. So it seems that `lintDirtyModulesOnly` does not work as intended with `fix`.

**Comment by ricardogobbosouza** [comment]
@thasmo Upgrade to latest version, if problem persists reopen this
