### ISSUE TITLE
Update peer dependencies to support stylelint 10

### ISSUE THREAD

**Issue by jimblue** [webpack-contrib/stylelint-webpack-plugin#174]
Hi there,

Stylelint v10 have been released with a lot of fix.
It could be nice if you update the peer dependencies and release a new npm version to support v10?

For now, I'm actually getting this on the console:

`npm WARN stylelint-webpack-plugin@0.10.5 requires a peer of stylelint@^8.0.0 but none is installed. You must install peer dependencies yourself.`

Cheers 👍

**Comment by dardinier** [comment]
I really agree with this issue.

@tagliala made a commit for fixing this. Could it be merged in this project ?

**Comment by tagliala** [comment]
@dardinier thanks. I can make a PR, but I would definitely not merge my commits.

I'm a newbie with webpack, and I'm pretty confident I've removed the compatibility to test against multiple webpack versions.

**Comment by dardinier** [comment]
@tagliala Ok I understand :)

Maybe showing interest about this issue will at least move things forward.

**Comment by jimblue** [comment]
Just a friendly ping... 😄
Is it possible to merge the PR and create a new release? 🎉
Cheers

**Comment by Preen** [comment]
+1

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/stylelint-webpack-plugin/issues/176

**Comment by jasonlav** [comment]
+1

**Comment by paul1k** [comment]
+1

**Comment by a-x-** [comment]
:-(

**Comment by Maorey** [comment]
+10086
