### ISSUE TITLE
Add "exclude" parttern support

### ISSUE THREAD

**Issue by vdloc** [webpack-contrib/stylelint-webpack-plugin#175]
* Operating System: Window 10
* Node Version: v10.15.0
* NPM Version: 6.8.0
* webpack Version: ^4.29.6
* stylelint-webpack-plugin Version:^0.10.5

This issue is for a:

- [ ] **bug**
- [x ] **feature** request
- [ ] **modification** request

##### CLI Command

```bash
  # paste the CLI command you're using. if this isn't applicable, it's safe to remove.
  $ {the command}
```

##### webpack.config.js

```js
  // If your bitchin' code blocks are over 20 lines, please paste a link to a gist
  // (https://gist.github.com).
```

### Expected Behavior
I expect an "exclude" feature to exclude folders/ files that I don't want to check by stylelint.

**Comment by ricardogobbosouza** [comment]
Hi @vdloc 
Use https://stylelint.io/user-guide/configuration#ignorefiles
