### ISSUE TITLE
Is this repo still maintain? need update about this library

### ISSUE THREAD

**Issue by jimblue** [webpack-contrib/stylelint-webpack-plugin#176]
Hi,

The last closed issue was on Juin 14th 2018. It's a year ago.
As for the repo/release, they both are one year old.

Can you give a little feedback to `stylelint-webpack-plugin` users to let us now if you still plan to maintain it?

Hope you understand what I'm looking for, just feedback basically. 😄 

Thank you so much,

Cheers

**Comment by evilebottnawi** [comment]
Sorry webpack team does not has time on maintaining this plugin, if somebody want to help us please write here

**Comment by odensc** [comment]
@evilebottnawi Hey, I'd be willing to help maintain/contribute if wanted. I use this plugin in a few of my projects.

**Comment by evilebottnawi** [comment]
@odensc thanks for feedback, how many time you have on maintenance this project? Anyway PR welcome and ping me when a PR need review, after couple of PRs you will be added as contributor and give permission to merge and release

**Comment by ricardogobbosouza** [comment]
@evilebottnawi 
I can help maintain this project.

**Comment by evilebottnawi** [comment]
@ricardogobbosouza how m

**Comment by ricardogobbosouza** [comment]
@evilebottnawi 
The same thing I dedicate to eslint-loader`, which I'm even refactoring to launch a v3

**Comment by evilebottnawi** [comment]
@ricardogobbosouza sent invite

**Comment by ricardogobbosouza** [comment]
thanks @evilebottnawi

**Comment by jimblue** [comment]
thank you both :) that a very good news!! 🎉 🎉
