### ISSUE TITLE
v1.0.0 not picking up file changes during recompilation

### ISSUE THREAD

**Issue by kyleschaeffer** [webpack-contrib/stylelint-webpack-plugin#184]
- Operating System: macOS 10.14.6
- Node Version: 10.16.3
- NPM Version: 6.9.0
- webpack Version: 4.29.6
- stylelint-webpack-plugin Version: 1.0.0

### Expected Behavior

I just updated to the new v1.0.0 that was released this morning (thanks for the work on this!). The new version works great for a single one-time build, but it's not picking up any changes that I make if I run the build process in watch mode using using `webpack-dev-server`.

### Actual Behavior

If I deliberately put in a linting error into a stylesheet, the error is reported as expected on one-time builds _and_ on the first build when running in watch mode. On subsequent "recompilation" builds, however, the old error still appears even if I delete the offending error from a stylesheet. The only way to get the linter to "refresh" the files, so to speak, is to stop and re-run the build script entirely.

### How Do We Reproduce?

Run `stylelint-webpack-plugin` using `webpack-dev-server` in watch mode.

**Comment by ricardogobbosouza** [comment]
@kyleschaeffer fixed on `v1.0.1`

**Comment by kyleschaeffer** [comment]
That was fast, thank you!

**Comment by ricardogobbosouza** [comment]
:smile:
