### ISSUE TITLE
styelint throws `No files matching the pattern` error with multiple exports from `webpack.config.js`

### ISSUE THREAD

**Issue by abhchand** [webpack-contrib/stylelint-webpack-plugin#191]
- Operating System: OSX Mojave (`10.14.2`)
- Node Version: `v10.16.0`
- NPM Version: `v6.9.0`
- webpack Version: `4.41.2`
- stylelint-webpack-plugin Version: `1.0.2`

### Background

Webpack supports building multiple outputs with it's multi-compiler feature outlined [here](https://stackoverflow.com/a/38132106/2490003).

I'm using this setup to build 2 output files - 

  - Build my core source file for distribution/production
  - Build an example of my component to use as a demo

### Expected Behavior

When I try to use stylelint as a webpack plugin with *multiple exports*, the build should succeed.

### Actual Behavior

When I try to use stylelint as a webpack plugin with *multiple exports*, the build fails with:

```
$ npm run build

> react-fancy-toggle@1.0.0 build /Users/abhishek/git/abhishek/react-fancy-toggle
> webpack --config webpack.config.js --mode production

Error: No files matching the pattern "/Users/abhishek/git/abhishek/react-fancy-toggle/src/Users/abhishek/git/abhishek/react-fancy-toggle/src/**/*.css" were found.
    at globby.then (/Users/abhishek/git/abhishek/react-fancy-toggle/node_modules/stylelint/lib/standalone.js:196:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-fancy-toggle@1.0.0 build: `webpack --config webpack.config.js --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-fancy-toggle@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/abhishek/.npm/_logs/2019-10-22T20_46_48_534Z-debug.log
```

Specifically it seems to be double-concatenting the path (`/Users/abhishek/git/abhishek/react-fancy-toggle/src`) and every combination of relative and absolute directory I try still causes it to fail.

### Code

```
var path = require('path');

const StyleLintPlugin = require('stylelint-webpack-plugin');

var ROOT_DIR = path.resolve(__dirname);
var LIB_DIR = path.resolve(__dirname, 'lib');
var SRC_DIR = path.resolve(__dirname, 'src');
var EXAMPLE_DIR = path.resolve(__dirname, 'examples');

// Common/Shared configs

var config = {
  resolve: {
    extensions: ['.js', '.jsx', '.sass', '.scss', '.css'],
    modules: [ SRC_DIR + '/css', SRC_DIR + '/js', 'node_modules' ]
  },
  resolveLoader: {
    modules: [ 'node_modules' ]
  },
  module: {
    strictExportPresence: true,
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader', 'eslint-loader']
      }
    ]
  },
  plugins: [
    new StyleLintPlugin({
      configFile: '.stylelintrc',
      context: 'src',
      files: '**/*.css',
      failOnError: false,
      quiet: false,
    })
  ],
};

// Configs for each output

var componentConfig = Object.assign({}, config, {
  entry: SRC_DIR + '/js/react-fancy-toggle.jsx',
  output: { path: LIB_DIR, filename: 'index.js' }
});

var simpleExampleConfig = Object.assign({}, config, {
  entry: EXAMPLE_DIR + '/simple/index.js',
  output: { path: EXAMPLE_DIR + '/simple', filename: 'bundle.js' }
});

module.exports = [
  componentConfig, simpleExampleConfig
];

```

### Observations

- The build fails regardless of how many `module.exports` entries there are. I tried it with one, two, and three exports.

- The build suceeds when `module.exports` is just a simple hash/config of one `config` object.

So perhaps it has to do with exporting an array of configs? 

I know projects like these take maintenance and work so really appreciate everyone that's contributed here! Stylelint is a fantastic piece of software.

**Comment by blephy** [comment]
Hi,

I'm getting this issue with the option `lintDirtyModulesOnly` set to `true`.

Webpack 5.11
Stylelint webpack plugin 2.1.1

**Comment by doomietrue** [comment]
Hello,

Also getting this errors.

"webpack": "^5.24.2",
 "stylelint-webpack-plugin": "^2.1.1"

**Comment by yisusans** [comment]
same - i'm getting the errors with
webpack: 5.21.0
stylelint-webpack-plugin: 2.1.1
