### ISSUE TITLE
Improve formatter option docs

### ISSUE THREAD

**Issue by TheIncorrigible1** [webpack-contrib/stylelint-webpack-plugin#201]
Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...

It is unclear what the API is for the `formatter` option besides that it takes a `Function`.

### Your Proposal for Changes

Since a lot of options are similar between this plugin and `eslint-loader`, perhaps [have a string option for different formatters](https://github.com/webpack-contrib/eslint-loader#formatter)?  Or improve documentation on what inputs/outputs are expected from the function passed to this option.

**Comment by ricardogobbosouza** [comment]
Hi @TheIncorrigible1 
I do not know if I understand
The options are the same as https://stylelint.io/user-guide/node-api#formatter
