### ISSUE TITLE
Error show up even if problem is already fixed

### ISSUE THREAD

**Issue by jimblue** [webpack-contrib/stylelint-webpack-plugin#218]
- Operating System: macOS Catalina v10.15.6
- Node Version: v12.18.3
- NPM Version: v6.14.6
- webpack Version: v4.44.1
- stylelint-webpack-plugin Version: v2.1.0

### Expected Behavior

Webpack should report error only once.

### Actual Behavior

Webpack is reporting an error twice.
One on first build and one even after the error is fixed.

### Code

[**webpack.config.js**](https://gist.github.com/jimblue/8c657fa6c74815fadbe13d17393cb889)

### How Do We Reproduce?

Run **webpack-dev-server** and remove a semicolon on a **SCSS file**.
After the first build, **Webpack** should output this error:

<img width="1017" alt="Screenshot 2020-08-31 at 20 45 30" src="https://user-images.githubusercontent.com/10623367/91764239-3f41e300-ebd7-11ea-80af-b50b62ad0d6c.png">

Then I add back the missing the semicolon to fix the error and save.
On the second build **Webpack** should output the same error but formatted differently:

<img width="1019" alt="Screenshot-2020-08-31-at-20 47 56" src="https://user-images.githubusercontent.com/10623367/91764392-829c5180-ebd7-11ea-9ad6-56e5794ca47c.png">

A this point the error is fixed but you should have to save a second time so **Webpack** can run a third build and the error should disappear.

When I don't use **stylelint-webpack-plugin** I only get the first error.

**Comment by evilebottnawi** [comment]
@jimblue It is expected, first error message from `stylelint`, second from `sass-loader`

**Comment by jimblue** [comment]
@evilebottnawi I think it's the contrary, first error from `sass-loader` and second from `stylelint` (because the second one never show up when disabling **stylelint**)

I don't understand why it's expected as for the second build the error is fixed... So none error should be output, neither `sass-loader` or `stylelint`.

Anyway this is super annoying don't you think ?
How can we fix that ?

**Comment by evilebottnawi** [comment]
No way, sass-loader and stylelint are different tools and no way to fix it, stylelint doesn't validate scss/sass syntax, but sass can't compile when syntax is broken

**Comment by jimblue** [comment]
I think only `stylelint`'s messages should be output when using `stylelint-webpack-plugin`.
First because they are more accurate and look better and are easier to understand.
Second because we don't need an error to be fired twice... the second is just just a false positive.

**Comment by jimblue** [comment]
> No way, sass-loader and stylelint are different tools and no way to fix it, stylelint doesn't validate scss/sass syntax, but sass can't compile when syntax is broken

OK I understand your point.
The problem has to be taken the other way.
When a `scss/sass` error show up on first build, if it's fixed for the second build then `stylelint` should not ouput an error.

**Comment by evilebottnawi** [comment]
Yes, as written above it is two difference tool, we can filter error from stylelint based on sass error and versa vice, you need to fix problem in code

**Comment by jimblue** [comment]
> Yes, as written above it is two difference tool, we can filter error from stylelint based on sass error and versa vice, you need to fix the problem in code

This is not what am saying...

I'm saying there is still a problem with this plugin :

1. first **Webpack** build of `main.scss` **=>** no error
2. second **Webpack** build of `main.scss` (with a missing semi-colon)  **=>** **sass-loader** error
3. third **Webpack** build of `main.scss` (with missing semi-colon fixed)  **=>** **stylelint** error

As you can see on step tree, `main.scss` file is fixed, so it Webpack should fire any error, neither from **sass** or **stylelint**.
And in fact **sass** work as espected, as no error is fired but **stylelint** still output an error when `main.scss` doesn't have any...

**Comment by jimblue** [comment]
@evilebottnawi ? 😄

**Comment by evilebottnawi** [comment]
@jimblue I already answered that it works as expected, what else do you expect?

**Comment by jimblue** [comment]
Sure I'll prepare a reproducible test repo 👍🏼

**Comment by ricardogobbosouza** [comment]
@jimblue 
Maybe fixed in #230

**Comment by ricardogobbosouza** [comment]
If you can give me feedback I would be grateful

**Comment by ricardogobbosouza** [comment]
Fixed in v2.2.0
