### ISSUE TITLE
webpack terminates watch if there is an error in the style files

### ISSUE THREAD

**Issue by ladarit** [webpack-contrib/stylelint-webpack-plugin#228]
Hello! Why does webpack stop "watch" if there is an error in the stylesheets? Other plugins that check code at build time, such as 'fork-ts-checker-webpack-plugin', throw an error if there is an error in the code, but the "watch" process does not terminate.
To be honest, it is extremely inconvenient to manually restart "watch" every time

**Comment by ricardogobbosouza** [comment]
Hi @ladarit 
Fixed in #230

**Comment by ricardogobbosouza** [comment]
Fixed in v2.2.0
