### ISSUE TITLE
Could you provide a compatible version of 2.x for stylelint 14?

### ISSUE THREAD

**Issue by yoyo837** [webpack-contrib/stylelint-webpack-plugin#248]

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/stylelint-webpack-plugin/pull/250

**Comment by ricardogobbosouza** [comment]
I think it's worth adding stylelint support in v2
Many projects still using webpack4

**Comment by ricardogobbosouza** [comment]
@yoyo837 added support for stylelint 14 on [v2.3.0](https://github.com/webpack-contrib/stylelint-webpack-plugin/releases/tag/v2.3.0)

**Comment by yoyo837** [comment]
> @yoyo837 added support for stylelint 14 on [v2.3.0](https://github.com/webpack-contrib/stylelint-webpack-plugin/releases/tag/v2.3.0)

Thanks for your great works.
