### ISSUE TITLE
Option ‘overrides’ dont't work!!! 

### ISSUE THREAD

**Issue by JowayYoung** [webpack-contrib/stylelint-webpack-plugin#255]
- Operating System: MacOS 10.15.7
- Node Version: 16.13.0
- NPM Version: 8.10.0
- webpack Version: 5.64.4
- stylelint-webpack-plugin Version: 3.1.0

### Bug report

'overrides => rules' don't work!!!

```js
const stylelintRules = { ... };
module.exports = function StylelintPlugin() {
	const { stylelintIgnores = [], stylelintRules = {} } = require(AbsPath("brucerc.js"));
	return new StylelintWebpackPlugin({
		cache: true,
		cacheLocation: AbsPath("node_modules/.cache/stylelint-webpack-plugin/.stylelintcache"),
		configFile: AbsPath("../templates/stylelint/stylelintrc.js", 1),
		context: AbsPath("src"),
		customSyntax: "postcss-scss",
		exclude: ["node_modules", ...stylelintIgnores].map(v => AbsPath(v)),
		extensions: ["css", "sass", "scss", "vue"],
		overrides: [{ rules: stylelintRules }], // overrides => invalid
		threads: true
	});
};
```

### Actual Behavior

I want to override the original rules through 'overrides => rules', but it does not take effect.

### Expected Behavior

'overrides => rules' can work!!!

**Comment by ricardogobbosouza** [comment]
Hi @JowayYoung 
You need to pass the files that will be overwritten

See https://stylelint.io/user-guide/configure#overrides
