### ISSUE TITLE
Stylelint does not ignore files inside build directory

### ISSUE THREAD

**Issue by Metastasis** [webpack-contrib/stylelint-webpack-plugin#267]
### Bug report

I'm trying to use multicompiler webpack feature in order to build several projects with one configuration. I'm also using stylelint, it's config and ignore files. When I'm trying to build those projects my build fails due to stylelint. Stylelint tries to lint css files inside build directory however I specified this build directory in .stylelintignore file

### Actual Behavior

Build fails because of stylelint errors

### Expected Behavior

Builds succeeds and stylelint ignores css files inside build directory

### How Do We Reproduce?

Check out this repo

https://github.com/Metastasis/stylelint-ignore-bug

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
  System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 524.16 MB / 16.00 GB
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 100.0.4896.75
    Firefox: 99.0
    Firefox Developer Edition: 95.0
    Safari: 15.2
  Monorepos:
    Lerna: 4.0.0
```

**Comment by ricardogobbosouza** [comment]
Hi @Metastasis 

The correct option is `ignorePath` instead of `ignoreFile`
https://github.com/Metastasis/stylelint-ignore-bug/blob/master/packages/webpack/webpack.config.js#L66

See 
https://stylelint.io/user-guide/usage/options/#ignorepath
https://stylelint.io/user-guide/configure/#ignorefiles

**Comment by Metastasis** [comment]
Thanks 👍
