### ISSUE TITLE
DeprecationWarning: [hash] is now [fullhash]

### ISSUE THREAD

**Issue by xavierfoucrier** [webpack-contrib/stylelint-webpack-plugin#285]
Hi @ricardogobbosouza,

Thanks for maintaining this project!

I recently got this deprecation warning when running `stylelint-webpack-plugin` in my webpack setup.

![image](https://user-images.githubusercontent.com/2471223/170281550-439d97cd-d161-4d31-b622-710f1dc74134.png)

Here is part of the environment / dependencies I use:
- `node` 16.15.0
- `npm` 8.10.0
- `stylelint` 14.8.5
- `stylelint-webpack-plugin` 3.3.0
- `webpack` 5.72.1
- `webpack-cli` 4.9.2

Thanks a lot for taking time to check on your side! :v:

**Comment by ricardogobbosouza** [comment]
Hi @xavierfoucrier 
Could you provide a repository?
I can't reproduce in a simple test

**Comment by xavierfoucrier** [comment]
Hello @ricardogobbosouza,

Thanks for your time!
I will provide a test repository as soon as possible :wink:

**Comment by vankop** [comment]
this is not related to stylelint plugin, this webpack core deprecation warning. this is expected changing from v4 to v5..

**Comment by xavierfoucrier** [comment]
Hello @ricardogobbosouza,

Unfortunately I can't reproduce myself, because since I post the issue I have updated/upgraded my dependencies.
I can just confirm that this is a webpack deprecation warning, rather than a stylelint deprecation warning... sorry!

> @vankop I was already using webpack 5 when I posted.
