### ISSUE TITLE
duplicate keys in 'rules' object surfaces confusing error

### ISSUE THREAD

**Issue by o2dazone** [webpack-contrib/stylelint-webpack-plugin#40]
I had 'block-no-empty' declared twice in my JSON `.stylelintrc.json`

The error I received is 
```
Error: Failed to parse "/Users/o2dazone/dev/app/.stylelintrc.json" as JSON, JS, or YAML.       
```

Running it through a validator made me realize I had duplicate keys. It's an easy fix on my side, and the error the plugin surfaced was kinda right, but it didn't really point me in the right direction on how to fix it, as my initial assumption had been a misconfiguration in the plugin config. This seemed to only effect the webpack plugin, as `stylelint` directly from the command line did not surface an error.

Feel free to close or set low priority 👍

**Comment by JaKXz** [comment]
Interesting, think you could reproduce it in a failing unit test? :)

**Comment by o2dazone** [comment]
I apologize if this is poor form, but I submitted a PR to invoke your Travis test
https://github.com/vieron/stylelint-webpack-plugin/pull/41

**Comment by JaKXz** [comment]
@o2dazone I just got your test to pass :) will be released in a new version soon, but would you mind installing stylelint-webpack-plugin#master and giving it a whirl?

**Comment by JaKXz** [comment]
To provide an update on this one, I took a crack at a PR to `cosmiconfig`, but the JSON error string comes from dependencies a couple levels upstream unfortunately: https://github.com/davidtheclark/cosmiconfig/pull/60

cc @zhaozhiming if you're interested in fixing a cosmiconfig issue :)

**Comment by o2dazone** [comment]
@JaKXz sorry I missed this - works great 👍

**Comment by shellscape** [comment]
Closing as stale due to age and inactivity. If there is still interest in this issue, please do submit a pull request.
