### ISSUE TITLE
Log to the browsers's console

### ISSUE THREAD

**Issue by ghost** [webpack-contrib/stylelint-webpack-plugin#45]
Is there a way to log the errors and warnings to the browser's console in addition to terminal's?

**Comment by JaKXz** [comment]
@vtfn thanks for the issue. I think this would be a good feature, would you like to investigate and perhaps open a PR? :)

**Comment by shellscape** [comment]
Closing as stale due to age and inactivity. If there is still interest in this issue, please do submit a pull request.
