### ISSUE TITLE
Lint on save

### ISSUE THREAD

**Issue by demrks** [webpack-contrib/stylelint-webpack-plugin#62]
I have the following folder structure

```
...
src/
  assets/
    css/
      ...
      components/
        test.css
      ...
      main.css
  ...
...
```

The `main.css` file imports the `test.css` file ("postcss-import"). My webpack config looks like this:

```javascript
module.export: {
  plugins: [
    new stylelintPlugin({
      context: 'src/assets/css',
      files: ['**/*.css']
    })
  ],
}
```

With this config, however, Stylelint will only lint my CSS files if I change the `main.css` file. If I change the `test.css` file (subdirectory), nothing happens. Is this how it's supposed to work or is there any config that I missed?

**Comment by JaKXz** [comment]
@demrks in my config I use a relative path from where the `webpack.config.js` is. Assuming your webpack is in the root of the repository, you should be able to change `context:` to `./src/assets/css` and it should work.

As the documentation says, [`context` is inherited from webpack](https://webpack.github.io/docs/context.html) so I think it's more of an advanced feature... I usually just specify a glob or array of globs in `files`.

**Comment by demrks** [comment]
@JaKXz Thanks. I already tried to remove `context` or set `files` to something like `files: ['**/*.css', './src/assets/css/subfolder/*.css']` but without success. 

For me, it will only run stylelint if I save the file that is included in my project (VueJS in my example with a `.vue` file and `<style src="./assets/css/main.css"></style>`). If I change this to a different file, it will only run stylelint if I change this file. I thought that the `files` option sets the files that trigger stylelint but I probably misunderstood this part. I will keep looking.

**Comment by shellscape** [comment]
Closing as stale due to age and inactivity. If there is still interest in this issue, please do submit a pull request.
