### ISSUE TITLE
Add support for CSS and LESS files by default

### ISSUE THREAD

**Issue by VovanR** [webpack-contrib/stylelint-webpack-plugin#8]
Current default regexp match `SCSS` and `SASS` files only

**Comment by barraponto** [comment]
I think supporting `css` should definitely be in by default.
Looking at [node-glob docs](https://github.com/isaacs/node-glob#glob-primer) i think the default should be `**/*.+(css|sass|scss|less)`. Of course we could do `**/*.+(c|sa|sc|le)ss` or something fancier like that, but I don't think it's worth ruining the legibility.

**Comment by shellscape** [comment]
Closing as stale due to age and inactivity. If there is still interest in this feature, please do submit a pull request.
