### ISSUE TITLE
UnhandledPromiseRejectionWarning, when no files match /**/*.s?(c|a)ss 

### ISSUE THREAD

**Issue by leosuncin** [webpack-contrib/stylelint-webpack-plugin#82]
The plugin fail when not found stylesheets for lint and break webpack build, this is a problem in some cases when you're starting a project without styles or embed styles in HTML

```
Error: /home/leosuncin/Workspaces/github/writtr-frontend/**/*.s?(c|a)ss does not match any files
(node:24485) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'emit' of undefined
(node:24485) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
The following tasks did not complete: serve, webpack:watch
Did you forget to signal async completion?
```

stylelint-webpack-plugin v0.7.0
webpack v2.5.1
gulp v3.9.1
node v7.7.3
npm v4.5.0
Manjaro GNU/Linux 17.0.1

You can clone [my repository](https://github.com/leosuncin/writtr-frontend/tree/writtr) and view the error

**Comment by JaKXz** [comment]
This might be an upstream issue with stylelint itself, because I _don't think_ there should be an unhandled rejection when a files are not found in the lint function. All this plugin does is call `stylelint.lint` and use the results, and if there's an error it should be contained in the error object that we print to the console.

**Comment by JaKXz** [comment]
That being said if you can reproduce it with a failing test in this repo, that would be awesome :)

**Comment by rondonjon** [comment]
@JaKXz, it's actually quite easy to reproduce. 

Same problem here. The plugin fails with an error if the context folder contains no stylesheets at all.

Admittedly, this may not be relevant for production builds, but it is quite annoying in other scenarios. For example, I've been running running tests cases on some of my application component with the same webpack configuration as for the actual application. After integrating stylelint-webpack-plugin, these test cases are now failing for all components that don't have stylesheets in their folders/subfolders.

**Comment by damianobarbati** [comment]
any news on this?

**Comment by Schlesiger** [comment]
+1

It's pretty important in scenarios with reusable `webpack` configurations. Several projects may share the same config but not all may have `.css` files.

**Comment by shellscape** [comment]
Closing as stale due to age and inactivity. If there is still interest in this issue, please do submit a pull request.
