### ISSUE TITLE
Can we use lintDirtyModulesOnly, but still lint on start?

### ISSUE THREAD

**Issue by higgins1b** [webpack-contrib/stylelint-webpack-plugin#85]
Thank you so much for this useful plugin.

Is there any way I can get the plugin to lint on start, then lint only the dirty modules on save?

Here is my current config:
```
config.plugins.unshift(
    new styleLintPlugin({
      configFile: '.stylelintrc',
      files: './packages/**/*.s?(a|c)ss',
      formatter: require('stylelint').formatters.verbose,
      lintDirtyModulesOnly: true,
      quiet: true,
      syntax: 'scss'
    })
  );
```
Thanks again!

**Comment by JaKXz** [comment]
To make the [`lintDirtyModulesOnly` configurable to allow first runs to happen](https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/lib/lint-dirty-modules-plugin.js#L17) I think could work, but you'd have to figure out how to keep track of the previous stats on the files. Feel free to take a crack at a PR, even just with some failing tests, I think this is a worthy enhancement. :)

cc @sergesemashko

**Comment by shellscape** [comment]
Closing as stale due to age and inactivity. If there is still interest in this issue, please do submit a pull request.

**Comment by AndrewCraswell** [comment]
I'm still interested in this, but we've just disabled the `lintDirtyModulesOnly` config in our build because it was preventing the `fix: true` config from working, and that was a much bigger blocker for us.

**Comment by patrickabkarian** [comment]
@JaKXz that's not what he means, he wants Stylelint to run normally once and then switch to linting dirty modules only.
