### ISSUE TITLE
Weird error "missed semicolon" with .sass syntax

### ISSUE THREAD

**Issue by soykje** [webpack-contrib/stylelint-webpack-plugin#95]
Hi everyone,

I just started a new project using this linter, and I'm having a weird issue for which I can't find any solution or explanation... :cry: 
So I am using Sass syntax (based on indentation), and for an unknown reason the lint give me a few errors saying "Missed semicolon - CssSyntaxError". I can't understand this as with Sass there is NO semicolon... Maybe something wrong with configuration ?
Thx in advance for your help!

**webpack.congif.js**
```
const path = require('path')
const webpack = require('webpack')

const ExtractTextPlugin = require('extract-text-webpack-plugin')
const StyleLintPlugin = require('stylelint-webpack-plugin')

module.exports = {
  entry: ['./src/index.js', './src/styles/index.sass'],
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: '/dist/'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: ['babel-loader', 'eslint-loader']
      },
      {
        test: /\.(sass|scss)$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            'css-loader',
            { loader: 'postcss-loader',
              options: {
                plugins: [
                  require('autoprefixer')()
                ]
              }
            },
            'sass-loader'
          ]
        })
      }
    ]
  },
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    }),
    new ExtractTextPlugin({
      filename: 'styles.css',
      disable: false,
      allChunks: true
    }),
    new StyleLintPlugin({
      syntax: 'scss',
      failOnError: true,
      quiet: false
    }),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production')
      }
    }),
    new webpack.optimize.UglifyJsPlugin()
  ],
  devServer: {
    contentBase: path.join(__dirname, '/')
  }
}
```
**.stylelintrc**

```
{
  "rules": {
    "indentation": 2
  }
}
```

**Comment by AndrewHaine** [comment]
Looks like this issue is with stylelint not completely supporting .sass syntax rather than an issue with the plugin itself. There is a [postcss-sass parser](https://github.com/AleshaOleg/postcss-sass) in development so looks like it's on the horizon, see stylelint/stylelint#2486 for more.

**Comment by AndrewHaine** [comment]
Temporary fix / Update 😃:
If you install the postcss-sass parser it can then be passed to the plugin through the customSyntax option - this fixes the 'Missed semicolon' message:
```JS
{
  customSyntax: path.join(__dirname, '/node_modules/postcss-sass'),
  ///...
}
```
The 'sass' option for 'syntax' isn't available in the latest stable stylelint release but the PR to add it has been merged to master so it's not far off

**Comment by shellscape** [comment]
@AndrewHaine thanks for the update (back in Feb). Please do let us know when that lands.

**Comment by AndrewHaine** [comment]
Hey @shellscape, this has been merged now (a while back actually sorry for not posting here) - SASS syntax now works alongside the others!

**Comment by shellscape** [comment]
Great, thanks for the follow-up!
